# Generated by Django 5.1.4 on 2024-12-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_artista_musica_delete_apellido_delete_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musica',
            new_name='Banda',
        ),
        migrations.RenameField(
            model_name='banda',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
